### ISSUE TITLE
runtime.py example.trt 모델 실행 에러

### ISSUE THREAD

**Issue by youngbaegi** [Nota-NetsPresso/NetsPresso-ModelSearch-Runtime#4]
NVIDIA Jetson Nano 보드에서 설치 가이드대로 진행했습니다만 아래와 같은 에러가 납니다. 뭐가 문제일지 혹시 아실까요?

```
Failed to load tf, tflite_runtime
[TensorRT] ERROR: coreReadArchive.cpp (38) - Serialization Error in verifyHeader: 0 (Version tag does not match)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
Traceback (most recent call last):
  File "runtime.py", line 472, in <module>
    model_wrapper.load_model()
  File "runtime.py", line 131, in load_model
    self.alloc_buf()
  File "runtime.py", line 151, in alloc_buf
    input_size = engine.get_binding_shape(0)[2:4] if engine.get_binding_shape(0)[1]==3 else input_shape[1:3]
AttributeError: 'NoneType' object has no attribute 'get_binding_shape'
```

**Comment by cbpark-nota** [comment]
먼저, 답변이 늦어진 점 죄송합니다. 담당자 퇴사 이후 관리가 제대로 이뤄지지 않는 repo 이다 보니 issue 를 확인하지 못 했네요.
engine 이 NoneType 인 것으로 보아 tensorrt 모델 자체가 로드되지 않은 것으로 보입니다. 
tensorrt 모델이 build 된 환경과 현재 실행환경이 버전이 다르거나, docker 를 사용하셨다면 --gpus 옵션을 주지 않은 것으로 보입니다.
제 개인적으로는 이런 경우 주로 환경의 버전 불일치인 경우가 많았는데요,
더 자세한 내용은 
```bash
[TensorRT] ERROR: coreReadArchive.cpp (38) - Serialization Error in verifyHeader: 0 (Version tag does not match)
```
이 내용으로 구글링 하셔서 찾아보시길 바랍니다.
